### ISSUE TITLE
Searching for more than one word in 'discover citations' and 'browse policy documents'

### ISSUE THREAD

**Issue by dd207** [wellcometrust/reach#382] opened 2020-02-03 10:10 UTC
Currently unable to retrieve results when searching for more than one word into the search bar for 'discover citations' and 'browse policy documents'.

Example: 
Searching for publication title 'A study of typhoid fever in five Asian countries' results in error page. 

Searching for a general topic 'typhoid' does retrieve matches for 'A study of typhoid fever in five Asian countries' but a user has to look through 80+ results to find that specific publication title.

**Comment by SamDepardieu** [comment] 2020-02-03 10:13
Alright - Looking int o this rn

**Comment by SamDepardieu** [comment] 2020-02-03 13:37
This is a duplicate of #381 , Closing this one as the other one is already label, in an epic etc.

**Closed by SamDepardieu** 2020-02-03 13:37 UTC
