### ISSUE TITLE
Final UI product QA

### ISSUE THREAD

**Issue by kristinenielsen** [wellcometrust/reach#549] opened 2020-06-08 09:20 UTC
Hi Jason,

Would be great if you can have a final review of the product keeping in mind of all these recent changes that was made. We can talk about timings
#518

**Comment by j-jaworski** [comment] 2020-06-09 13:49
Below are the issues that I have spotted. I recommend that everyone get's involved in the QA before Alpha release, going through key user journeys, testing its robustness. I am sure to have missed somethings.

Visually I think it is looking good enough for release, but there are a couple of biggies IMO – the sorting, pagination and open rows do not behave as expected, I can see this causing some confusion for users.

**Homepage**

1. H3 heading should be `bold`
2. New Logo make smaller - same size as other pages. Looks very big here

**About Reach**

3. `<p>` under "Open source", "Accuracy" and "Transparency" to be left-aligned

**/search/citations and /search/policy-docs**

4. Increase padding left and right in button to `16px`
5. Force line breaks in H1 and H3 as below using &nbsp;

![Screenshot 2020-06-09 at 13.54.30.jpg](https://images.zenhubusercontent.com/5bcdab41ba9b001064ad8afc/7156f816-e30b-4622-ab15-b23c8aafa314)

![Screenshot 2020-06-09 at 13.56.33.jpg](https://images.zenhubusercontent.com/5bcdab41ba9b001064ad8afc/e4f9c983-c2c1-4280-a5db-c0dda399182c)

**Citations results**

6. Need hover states on pagination elements
7. Column headers eg "Journal" should be the trigger for sorting, not just icon
8. Can't close a row once it has expanded
9. Sorting - icon should not change until the results have loaded
10. loading animation timing feels off
11. Sorting doesn't seem to rearrange the results
12. Sorting icons need padding around them
13. Open rows not staying open when clicked
14. Column headers in open rows should match other column headers
15. Next button doesn't seem to work (maybe just super slow)
16. Pagination number eg "2" doesn't go to next page
17. Search button on input field "Discover citations" increase padding left and right by 16px

**Comment by SamDepardieu** [comment] 2020-06-09 14:27
@j-jaworski : I checked a few things:

- Pages changes are slow, but I can confirm that on my side, both clicking Prev/Next buttons or a page number works. Maybe we should start the progress animation from the click for the time being, to notify the click had an effect?

- On my side column headers are triggers for sorting, althouh it also is slower than it was

- `loading animation timing feels off `->  Are you talking about the progress bar? If so, it should be starting 2sec after an action, as requested in last QA 

- About rows on-click behaviour: `Open rows not staying open when clicked` Should we leave opened rows open? I thought the behaviour we choose was "opening one closes the others", sorry if I missunderstood that

Everything else is clear and will be fixed this week :+1:

**Comment by aoifespenge** [comment] 2020-06-09 15:09
Emanuela spotted this one: https://github.com/wellcometrust/reach/issues/553

**Comment by lizgzil** [comment] 2020-06-09 16:47
I hope I'm looking at the correct version (https://reach-staging.wellcomedatalabs.org/) ?
Things I spotted, I think the last 2 might be for a separate discussion:
- "Our entire code can be found on Github " on home page - GitHub is written with a capital H
- in '/about' at the end of the "What are the scientific publications?" paragraph, "Click here to find more about How Reach Works" doesn't have any link.
- in 'search/citations' and 'search/policy-docs' if there is only one page of results the '>' is still in dark blue and I guess should be in light blue (see screenshot)
![Screenshot 2020-06-09 at 17 26 30](https://user-images.githubusercontent.com/15956065/84174528-9fad0280-aa76-11ea-8011-d52baf09c5dc.png)
- in 'search/citations' the heading 'journal' is spelt 'jounal'
- seems like the authors list in 'search/citations' need spaces between them?
- 'organisation WHO IRIS' in 'search/policy-docs', arguably the organisation is just WHO.
- I know there is a separate convo going on about not including results from publications with no policy citations - so just a comment on the fact that when there are no policy citations so you can't expand the list, it means you can't see the whole title or author field texts.
- I expect this is out of scope for now - but since some of these searches can yield large numbers of results, in the 'download' tab I would personally want a pop-up of 'do you want to download 1,00,000 results? Yes No', for those times you accidentally click to download 10GB of data and don't get prompted to reconsider

Regardless, I think it looks great and can't wait for it to be release!

**Comment by j-jaworski** [comment] 2020-06-10 11:14
@SamDepardieu Thanks for going through these

• Pages changes being slow, sorting be slow and points about the animation are all related – I think having the progress bar from click for these interactions would help. We should also not change the sort icon until after the loading animation
• My point about the loading animation was to do with this 👆🏻 we should if possible, keep the 2 sec delay for loading animation on the initial search as previously it was interrupting the results when it wasn't needed.
• Yes only one open row at a time, but when I was opening a row it was closing of its own accord

Hope this provides some clarity, let me know if you need anything else

**Comment by SamDepardieu** [comment] 2020-06-11 09:19
This should all be addressed in #556, closing

**Closed by SamDepardieu** 2020-06-11 09:19 UTC
